GOOGLE_APP_ID: '52872426518-h5dibra2poitt9pmkufrjpun7uj7m1nj.apps.googleusercontent.com'

GOOGLE_APP_SECRET: 'Hl2FjFI8w33SUqCsJRAnpWjx'

S3_BUCKET_NAME: parkers-kl
AWS_ACCESS_KEY_ID: AKIAJ5J6CXSWCSH3MDEA
AWS_SECRET_ACCESS_KEY: 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
AWS_REGION: us-east-1
